########################################################################################################################
## -- first we build and run the generator, which is responsible for producing all the source packages,
##    for all java versions, for all OS's (debian/ubuntu) and for all distribuitions (xenial/trusty/jessie/etc)
FROM node:12-alpine as generator

# First, only package.json and lockfile, so we docker-layer-cache npm dependencies.
ADD generator/package*.json /gen/generator/
WORKDIR /gen/generator
RUN npm install

# Then the rest of the generator app and the templates...
ADD generator/generate.js /gen/generator/generate.js
ADD templates /gen/templates
# ... and then run the generator.
RUN node generate.js
#RUN ls -laR /gen/generated/debian
#RUN exit 1


########################################################################################################################
## -- Now its the Ubuntu package builder's turn.
##    We use bionic here, but supposedly any could be used,
##    since the packages are so simple.
FROM ubuntu:bionic as ubuntuBuilder
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update
# build-time dependencies
RUN apt-get -y --no-install-recommends install devscripts build-essential lintian debhelper fakeroot lsb-release figlet
# install-time dependencies (those are listed in Depends or Pre-Depends in debian/control file)
RUN apt-get -y --no-install-recommends install java-common wget locales ca-certificates
WORKDIR /opt/adoptopenjdk/ubuntu
COPY --from=generator /gen/generated/ubuntu /opt/adoptopenjdk/ubuntu
#RUN ls -laR /opt/adoptopenjdk/ubuntu
ADD docker/build_packages_multi.sh /opt/adoptopenjdk/
# those will be populated by the build script.
RUN mkdir -p /binaries /sourcepkg
RUN /opt/adoptopenjdk/build_packages_multi.sh ubuntu


########################################################################################################################
## -- Now its the Debian package builder's turn.
##    We use jessie here, but supposedly any could be used,
##    since the packages are so simple.
FROM debian:jessie as debianBuilder
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update
# build-time dependencies
RUN apt-get -y --no-install-recommends install devscripts build-essential lintian debhelper fakeroot lsb-release figlet parallel
# install-time dependencies (those are listed in Depends or Pre-Depends in debian/control file)
RUN apt-get -y --no-install-recommends install java-common wget locales ca-certificates libxrender1 libxtst6 libxi6 libfontconfig1 libasound2
WORKDIR /opt/adoptopenjdk/debian

### VERSION SPECIFIC -- generated by generate.js in stdout
RUN mkdir -p /var/cache/adoptopenjdk-8-jdk-openj9-installer /var/cache/adoptopenjdk-8-jdk-hotspot-installer /var/cache/adoptopenjdk-8-jre-openj9-installer /var/cache/adoptopenjdk-8-jre-hotspot-installer /var/cache/adoptopenjdk-9-jdk-hotspot-installer /var/cache/adoptopenjdk-9-jre-hotspot-installer /var/cache/adoptopenjdk-11-jre-openj9-installer /var/cache/adoptopenjdk-11-jdk-openj9-installer /var/cache/adoptopenjdk-10-jdk-hotspot-installer /var/cache/adoptopenjdk-10-jre-hotspot-installer /var/cache/adoptopenjdk-13-jre-openj9-installer /var/cache/adoptopenjdk-12-jdk-openj9-installer /var/cache/adoptopenjdk-14-jre-openj9-installer /var/cache/adoptopenjdk-13-jdk-openj9-installer /var/cache/adoptopenjdk-11-jdk-hotspot-installer /var/cache/adoptopenjdk-11-jre-hotspot-installer /var/cache/adoptopenjdk-14-jdk-openj9-installer /var/cache/adoptopenjdk-12-jdk-hotspot-installer /var/cache/adoptopenjdk-13-jre-hotspot-installer /var/cache/adoptopenjdk-14-jre-hotspot-installer /var/cache/adoptopenjdk-13-jdk-hotspot-installer /var/cache/adoptopenjdk-14-jdk-hotspot-installer
RUN (echo wget --continue --local-encoding=UTF-8 --progress=dot:giga -O /var/cache/adoptopenjdk-8-jdk-openj9-installer/OpenJDK8U-jdk_x64_linux_openj9_8u242b08_openj9-0.18.1.tar.gz "http://192.168.66.100/down/aoj/OpenJDK8U-jdk_x64_linux_openj9_8u242b08_openj9-0.18.1.tar.gz";echo wget --continue --local-encoding=UTF-8 --progress=dot:giga -O /var/cache/adoptopenjdk-8-jdk-hotspot-installer/OpenJDK8U-jdk_x64_linux_hotspot_8u242b08.tar.gz "http://192.168.66.100/down/aoj/OpenJDK8U-jdk_x64_linux_hotspot_8u242b08.tar.gz";echo wget --continue --local-encoding=UTF-8 --progress=dot:giga -O /var/cache/adoptopenjdk-8-jre-openj9-installer/OpenJDK8U-jre_x64_linux_openj9_8u242b08_openj9-0.18.1.tar.gz "http://192.168.66.100/down/aoj/OpenJDK8U-jre_x64_linux_openj9_8u242b08_openj9-0.18.1.tar.gz";echo wget --continue --local-encoding=UTF-8 --progress=dot:giga -O /var/cache/adoptopenjdk-8-jre-hotspot-installer/OpenJDK8U-jre_x64_linux_hotspot_8u242b08.tar.gz "http://192.168.66.100/down/aoj/OpenJDK8U-jre_x64_linux_hotspot_8u242b08.tar.gz";echo wget --continue --local-encoding=UTF-8 --progress=dot:giga -O /var/cache/adoptopenjdk-9-jdk-hotspot-installer/OpenJDK9U-jdk_x64_linux_hotspot_9.0.4_11.tar.gz "http://192.168.66.100/down/aoj/OpenJDK9U-jdk_x64_linux_hotspot_9.0.4_11.tar.gz";echo wget --continue --local-encoding=UTF-8 --progress=dot:giga -O /var/cache/adoptopenjdk-9-jre-hotspot-installer/OpenJDK9U-jre_x64_linux_hotspot_9.0.4_11.tar.gz "http://192.168.66.100/down/aoj/OpenJDK9U-jre_x64_linux_hotspot_9.0.4_11.tar.gz";echo wget --continue --local-encoding=UTF-8 --progress=dot:giga -O /var/cache/adoptopenjdk-11-jre-openj9-installer/OpenJDK11U-jre_x64_linux_openj9_11.0.6_10_openj9-0.18.1.tar.gz "http://192.168.66.100/down/aoj/OpenJDK11U-jre_x64_linux_openj9_11.0.6_10_openj9-0.18.1.tar.gz";echo wget --continue --local-encoding=UTF-8 --progress=dot:giga -O /var/cache/adoptopenjdk-11-jdk-openj9-installer/OpenJDK11U-jdk_x64_linux_openj9_11.0.6_10_openj9-0.18.1.tar.gz "http://192.168.66.100/down/aoj/OpenJDK11U-jdk_x64_linux_openj9_11.0.6_10_openj9-0.18.1.tar.gz";echo wget --continue --local-encoding=UTF-8 --progress=dot:giga -O /var/cache/adoptopenjdk-10-jdk-hotspot-installer/OpenJDK10_x64_Linux_jdk-10.0.2+13.tar.gz "http://192.168.66.100/down/aoj/OpenJDK10_x64_Linux_jdk-10.0.2+13.tar.gz";echo wget --continue --local-encoding=UTF-8 --progress=dot:giga -O /var/cache/adoptopenjdk-10-jre-hotspot-installer/OpenJDK10U-jre_x64_linux_hotspot_10.0.2_13.tar.gz "http://192.168.66.100/down/aoj/OpenJDK10U-jre_x64_linux_hotspot_10.0.2_13.tar.gz";echo wget --continue --local-encoding=UTF-8 --progress=dot:giga -O /var/cache/adoptopenjdk-13-jre-openj9-installer/OpenJDK13U-jre_x64_linux_openj9_13.0.2_8_openj9-0.18.0.tar.gz "http://192.168.66.100/down/aoj/OpenJDK13U-jre_x64_linux_openj9_13.0.2_8_openj9-0.18.0.tar.gz";echo wget --continue --local-encoding=UTF-8 --progress=dot:giga -O /var/cache/adoptopenjdk-12-jdk-openj9-installer/OpenJDK12U-jdk_x64_linux_openj9_12.0.2_10_openj9-0.15.1.tar.gz "http://192.168.66.100/down/aoj/OpenJDK12U-jdk_x64_linux_openj9_12.0.2_10_openj9-0.15.1.tar.gz";echo wget --continue --local-encoding=UTF-8 --progress=dot:giga -O /var/cache/adoptopenjdk-14-jre-openj9-installer/OpenJDK14U-jre_x64_linux_openj9_14_36_openj9-0.19.0.tar.gz "http://192.168.66.100/down/aoj/OpenJDK14U-jre_x64_linux_openj9_14_36_openj9-0.19.0.tar.gz";echo wget --continue --local-encoding=UTF-8 --progress=dot:giga -O /var/cache/adoptopenjdk-13-jdk-openj9-installer/OpenJDK13U-jdk_x64_linux_openj9_13.0.2_8_openj9-0.18.0.tar.gz "http://192.168.66.100/down/aoj/OpenJDK13U-jdk_x64_linux_openj9_13.0.2_8_openj9-0.18.0.tar.gz";echo wget --continue --local-encoding=UTF-8 --progress=dot:giga -O /var/cache/adoptopenjdk-11-jdk-hotspot-installer/OpenJDK11U-jdk_x64_linux_hotspot_11.0.6_10.tar.gz "http://192.168.66.100/down/aoj/OpenJDK11U-jdk_x64_linux_hotspot_11.0.6_10.tar.gz";echo wget --continue --local-encoding=UTF-8 --progress=dot:giga -O /var/cache/adoptopenjdk-11-jre-hotspot-installer/OpenJDK11U-jre_x64_linux_hotspot_11.0.6_10.tar.gz "http://192.168.66.100/down/aoj/OpenJDK11U-jre_x64_linux_hotspot_11.0.6_10.tar.gz";echo wget --continue --local-encoding=UTF-8 --progress=dot:giga -O /var/cache/adoptopenjdk-14-jdk-openj9-installer/OpenJDK14U-jdk_x64_linux_openj9_14_36_openj9-0.19.0.tar.gz "http://192.168.66.100/down/aoj/OpenJDK14U-jdk_x64_linux_openj9_14_36_openj9-0.19.0.tar.gz";echo wget --continue --local-encoding=UTF-8 --progress=dot:giga -O /var/cache/adoptopenjdk-12-jdk-hotspot-installer/OpenJDK12U-jdk_x64_linux_hotspot_12.0.2_10.tar.gz "http://192.168.66.100/down/aoj/OpenJDK12U-jdk_x64_linux_hotspot_12.0.2_10.tar.gz";echo wget --continue --local-encoding=UTF-8 --progress=dot:giga -O /var/cache/adoptopenjdk-13-jre-hotspot-installer/OpenJDK13U-jre_x64_linux_hotspot_13.0.2_8.tar.gz "http://192.168.66.100/down/aoj/OpenJDK13U-jre_x64_linux_hotspot_13.0.2_8.tar.gz";echo wget --continue --local-encoding=UTF-8 --progress=dot:giga -O /var/cache/adoptopenjdk-14-jre-hotspot-installer/OpenJDK14U-jre_x64_linux_hotspot_14_36.tar.gz "http://192.168.66.100/down/aoj/OpenJDK14U-jre_x64_linux_hotspot_14_36.tar.gz";echo wget --continue --local-encoding=UTF-8 --progress=dot:giga -O /var/cache/adoptopenjdk-13-jdk-hotspot-installer/OpenJDK13U-jdk_x64_linux_hotspot_13.0.2_8.tar.gz "http://192.168.66.100/down/aoj/OpenJDK13U-jdk_x64_linux_hotspot_13.0.2_8.tar.gz";echo wget --continue --local-encoding=UTF-8 --progress=dot:giga -O /var/cache/adoptopenjdk-14-jdk-hotspot-installer/OpenJDK14U-jdk_x64_linux_hotspot_14_36.tar.gz "http://192.168.66.100/down/aoj/OpenJDK14U-jdk_x64_linux_hotspot_14_36.tar.gz") | parallel -j 8 --progress --eta --line-buffer

COPY --from=generator /gen/generated/debian /opt/adoptopenjdk/debian
ADD docker/build_packages_multi.sh /opt/adoptopenjdk/
# those will be populated by the build script.
RUN mkdir -p /binaries /sourcepkg
RUN /opt/adoptopenjdk/build_packages_multi.sh debian


########################################################################################################################
## -- the final image produced from this Dockerfile just contains the produced source and binary packages.
##    it uses alpine:3.8 because that's light enough, and already downloaded for node:10-alpine
FROM alpine:3.8

COPY --from=ubuntuBuilder /sourcepkg/* /sourcepkg/
COPY --from=debianBuilder /binaries/* /binaries/

# Hack: use volumes to "exfiltrate" the source files back to the host machine.
# This is just a marker directory to avoid mistakes when mounting volumes.
RUN mkdir -p /exfiltrate_to/empty

# Simple script to exfiltrate on run.
COPY docker/exfiltrate.sh /opt/exfiltrate.sh
CMD /opt/exfiltrate.sh
