########################################################################################################################
## -- first we build and run the generator, which is responsible for producing all the source packages,
##    for all java versions, for all OS's (debian/ubuntu) and for all distribuitions (xenial/trusty/jessie/etc)
FROM node:10-alpine as generator

# First, only package.json and lockfile, so we docker-layer-cache npm dependencies.
ADD generator/package*.json /gen/generator/
WORKDIR /gen/generator
RUN npm install

# A first-stage minimal "cacher" so we can develop against cached versions.
ADD generator/populate_cache.js /gen/generator/populate_cache.js
RUN node populate_cache.js

# Then the rest of the generator app and the templates...
ADD generator/generate.js /gen/generator/generate.js
ADD templates /gen/templates
# ... and then run the generator.
RUN node generate.js
#RUN ls -laR /gen/generated/debian


########################################################################################################################
## -- Now its the Ubuntu package builder's turn.
##    We use bionic here, but supposedly any could be used,
##    since the packages are so simple.
FROM ubuntu:bionic as ubuntuBuilder
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update
# build-time dependencies
RUN apt-get -y --no-install-recommends install devscripts build-essential lintian debhelper fakeroot lsb-release figlet
# install-time dependencies (those are listed in Depends or Pre-Depends in debian/control file)
RUN apt-get -y --no-install-recommends install java-common wget locales ca-certificates
WORKDIR /opt/adoptopenjdk/ubuntu
COPY --from=generator /gen/generated/ubuntu /opt/adoptopenjdk/ubuntu
#RUN ls -laR /opt/adoptopenjdk/ubuntu
ADD docker/build_packages_multi.sh /opt/adoptopenjdk/
# those will be populated by the build script.
RUN mkdir -p /binaries /sourcepkg
RUN /opt/adoptopenjdk/build_packages_multi.sh ubuntu


########################################################################################################################
## -- Now its the Debian package builder's turn.
##    We use jessie here, but supposedly any could be used,
##    since the packages are so simple.
FROM debian:jessie as debianBuilder
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update
# build-time dependencies
RUN apt-get -y --no-install-recommends install devscripts build-essential lintian debhelper fakeroot lsb-release figlet parallel
# install-time dependencies (those are listed in Depends or Pre-Depends in debian/control file)
RUN apt-get -y --no-install-recommends install java-common wget locales ca-certificates libxrender1 libxtst6 libxi6 libfontconfig1 libasound2
WORKDIR /opt/adoptopenjdk/debian

### VERSION SPECIFIC -- generated by populate_cache.js in stdout
RUN mkdir -p /var/cache/adoptopenjdk-8-jdk-hotspot-installer /var/cache/adoptopenjdk-9-jdk-hotspot-installer /var/cache/adoptopenjdk-10-jdk-hotspot-installer /var/cache/adoptopenjdk-11-jdk-hotspot-installer /var/cache/adoptopenjdk-12-jdk-hotspot-installer /var/cache/adoptopenjdk-8-jdk-openj9-installer /var/cache/adoptopenjdk-11-jdk-openj9-installer /var/cache/adoptopenjdk-12-jdk-openj9-installer /var/cache/adoptopenjdk-8-jre-hotspot-installer /var/cache/adoptopenjdk-9-jre-hotspot-installer /var/cache/adoptopenjdk-11-jre-hotspot-installer /var/cache/adoptopenjdk-12-jre-hotspot-installer /var/cache/adoptopenjdk-8-jre-openj9-installer /var/cache/adoptopenjdk-11-jre-openj9-installer /var/cache/adoptopenjdk-12-jre-openj9-installer
RUN (echo wget --continue --local-encoding=UTF-8 -O /var/cache/adoptopenjdk-8-jdk-hotspot-installer/OpenJDK8U-jdk_x64_linux_hotspot_8u212b03.tar.gz "https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u212-b03/OpenJDK8U-jdk_x64_linux_hotspot_8u212b03.tar.gz";echo wget --continue --local-encoding=UTF-8 -O /var/cache/adoptopenjdk-9-jdk-hotspot-installer/OpenJDK9U-jdk_x64_linux_hotspot_9.0.4_11.tar.gz "https://github.com/AdoptOpenJDK/openjdk9-binaries/releases/download/jdk-9.0.4%2B11/OpenJDK9U-jdk_x64_linux_hotspot_9.0.4_11.tar.gz";echo wget --continue --local-encoding=UTF-8 -O /var/cache/adoptopenjdk-10-jdk-hotspot-installer/OpenJDK10_x64_Linux_jdk-10.0.2+13.tar.gz "https://github.com/AdoptOpenJDK/openjdk10-releases/releases/download/jdk-10.0.2%2B13/OpenJDK10_x64_Linux_jdk-10.0.2%2B13.tar.gz";echo wget --continue --local-encoding=UTF-8 -O /var/cache/adoptopenjdk-11-jdk-hotspot-installer/OpenJDK11U-jdk_x64_linux_hotspot_11.0.3_7.tar.gz "https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.3%2B7/OpenJDK11U-jdk_x64_linux_hotspot_11.0.3_7.tar.gz";echo wget --continue --local-encoding=UTF-8 -O /var/cache/adoptopenjdk-12-jdk-hotspot-installer/OpenJDK12U-jdk_x64_linux_hotspot_12.0.1_12.tar.gz "https://github.com/AdoptOpenJDK/openjdk12-binaries/releases/download/jdk-12.0.1%2B12/OpenJDK12U-jdk_x64_linux_hotspot_12.0.1_12.tar.gz";echo wget --continue --local-encoding=UTF-8 -O /var/cache/adoptopenjdk-8-jdk-openj9-installer/OpenJDK8U-jdk_x64_linux_openj9_8u212b03_openj9-0.14.0.tar.gz "https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u212-b03_openj9-0.14.0/OpenJDK8U-jdk_x64_linux_openj9_8u212b03_openj9-0.14.0.tar.gz";echo wget --continue --local-encoding=UTF-8 -O /var/cache/adoptopenjdk-11-jdk-openj9-installer/OpenJDK11U-jdk_x64_linux_openj9_11.0.3_7_openj9-0.14.0.tar.gz "https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.3%2B7_openj9-0.14.0/OpenJDK11U-jdk_x64_linux_openj9_11.0.3_7_openj9-0.14.0.tar.gz";echo wget --continue --local-encoding=UTF-8 -O /var/cache/adoptopenjdk-12-jdk-openj9-installer/OpenJDK12U-jdk_x64_linux_openj9_12.0.1_12_openj9-0.14.1.tar.gz "https://github.com/AdoptOpenJDK/openjdk12-binaries/releases/download/jdk-12.0.1%2B12_openj9-0.14.1/OpenJDK12U-jdk_x64_linux_openj9_12.0.1_12_openj9-0.14.1.tar.gz";echo wget --continue --local-encoding=UTF-8 -O /var/cache/adoptopenjdk-8-jre-hotspot-installer/OpenJDK8U-jre_x64_linux_hotspot_8u212b03.tar.gz "https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u212-b03/OpenJDK8U-jre_x64_linux_hotspot_8u212b03.tar.gz";echo wget --continue --local-encoding=UTF-8 -O /var/cache/adoptopenjdk-9-jre-hotspot-installer/OpenJDK9U-jre_x64_linux_hotspot_9.0.4_11.tar.gz "https://github.com/AdoptOpenJDK/openjdk9-binaries/releases/download/jdk-9.0.4%2B11/OpenJDK9U-jre_x64_linux_hotspot_9.0.4_11.tar.gz";echo wget --continue --local-encoding=UTF-8 -O /var/cache/adoptopenjdk-11-jre-hotspot-installer/OpenJDK11U-jre_x64_linux_hotspot_11.0.3_7.tar.gz "https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.3%2B7/OpenJDK11U-jre_x64_linux_hotspot_11.0.3_7.tar.gz";echo wget --continue --local-encoding=UTF-8 -O /var/cache/adoptopenjdk-12-jre-hotspot-installer/OpenJDK12U-jre_x64_linux_hotspot_12.0.1_12.tar.gz "https://github.com/AdoptOpenJDK/openjdk12-binaries/releases/download/jdk-12.0.1%2B12/OpenJDK12U-jre_x64_linux_hotspot_12.0.1_12.tar.gz";echo wget --continue --local-encoding=UTF-8 -O /var/cache/adoptopenjdk-8-jre-openj9-installer/OpenJDK8U-jre_x64_linux_openj9_8u212b03_openj9-0.14.0.tar.gz "https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u212-b03_openj9-0.14.0/OpenJDK8U-jre_x64_linux_openj9_8u212b03_openj9-0.14.0.tar.gz";echo wget --continue --local-encoding=UTF-8 -O /var/cache/adoptopenjdk-11-jre-openj9-installer/OpenJDK11U-jre_x64_linux_openj9_11.0.3_7_openj9-0.14.0.tar.gz "https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.3%2B7_openj9-0.14.0/OpenJDK11U-jre_x64_linux_openj9_11.0.3_7_openj9-0.14.0.tar.gz";echo wget --continue --local-encoding=UTF-8 -O /var/cache/adoptopenjdk-12-jre-openj9-installer/OpenJDK12U-jre_x64_linux_openj9_12.0.1_12_openj9-0.14.1.tar.gz "https://github.com/AdoptOpenJDK/openjdk12-binaries/releases/download/jdk-12.0.1%2B12_openj9-0.14.1/OpenJDK12U-jre_x64_linux_openj9_12.0.1_12_openj9-0.14.1.tar.gz") | parallel -j 15 --progress --eta --line-buffer


COPY --from=generator /gen/generated/debian /opt/adoptopenjdk/debian
ADD docker/build_packages_multi.sh /opt/adoptopenjdk/
# those will be populated by the build script.
RUN mkdir -p /binaries /sourcepkg
RUN /opt/adoptopenjdk/build_packages_multi.sh debian


########################################################################################################################
## -- the final image produced from this Dockerfile just contains the produced source and binary packages.
##    it uses alpine:3.8 because that's light enough, and already downloaded for node:10-alpine
FROM alpine:3.8

COPY --from=ubuntuBuilder /sourcepkg/* /sourcepkg/
COPY --from=debianBuilder /binaries/* /binaries/

# Hack: use volumes to "exfiltrate" the source files back to the host machine.
# This is just a marker directory to avoid mistakes when mounting volumes.
RUN mkdir -p /exfiltrate_to/empty

# Simple script to exfiltrate on run.
COPY docker/exfiltrate.sh /opt/exfiltrate.sh
CMD /opt/exfiltrate.sh
