########################################################################################################################
## -- first we build and run the generator, which is responsible for producing all the source packages,
##    for all java versions, for all OS's (debian/ubuntu) and for all distribuitions (xenial/trusty/jessie/etc)
FROM node:14-alpine as generator

# First, only package.json and lockfile, so we docker-layer-cache npm dependencies.
ADD generator/package*.json /gen/generator/
WORKDIR /gen/generator
RUN npm install

# Then the rest of the generator app and the templates...
ADD generator/generate.js /gen/generator/generate.js
ADD templates /gen/templates
# ... and then run the generator.
RUN node generate.js
#RUN ls -laR /gen/generated/debian
#RUN exit 1


########################################################################################################################
## -- Now its the Ubuntu package builder's turn.
##    We use bionic here, but supposedly any could be used
FROM ubuntu:bionic as ubuntuBuilder
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update
# build-time dependencies
RUN apt-get -y --no-install-recommends install eatmydata devscripts build-essential lintian debhelper fakeroot lsb-release figlet
# install-time dependencies (those are listed in Depends or Pre-Depends in debian/control file)
RUN apt-get -y --no-install-recommends install java-common wget locales ca-certificates
WORKDIR /opt/adoptium/ubuntu
COPY --from=generator /gen/generated/ubuntu /opt/adoptium/ubuntu
#RUN ls -laR /opt/adoptium/ubuntu
ADD docker/build_packages_multi.sh /opt/adoptium/
# those will be populated by the build script.
RUN mkdir -p /binaries /sourcepkg
RUN /opt/adoptium/build_packages_multi.sh ubuntu


########################################################################################################################
## -- Now its the Debian package builder's turn.
##    We use jessie here, but supposedly any could be used,
##    since the packages are so simple.
FROM debian:jessie as debianBuilder
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update
# build-time dependencies
RUN apt-get -y --no-install-recommends install eatmydata devscripts build-essential lintian debhelper fakeroot lsb-release figlet parallel
# install-time dependencies (those are listed in Depends or Pre-Depends in debian/control file)
RUN apt-get -y --no-install-recommends install java-common wget locales ca-certificates libxrender1 libxtst6 libxi6 libfontconfig1 libasound2
WORKDIR /opt/adoptium/debian

### VERSION SPECIFIC -- generated by generate.js in stdout (@TODO: ???)

COPY --from=generator /gen/generated/debian /opt/adoptium/debian
ADD docker/build_packages_multi.sh /opt/adoptium/
# those will be populated by the build script.
RUN mkdir -p /binaries /sourcepkg
RUN /opt/adoptium/build_packages_multi.sh debian


########################################################################################################################
## -- the final image produced from this Dockerfile just contains the produced source and binary packages.
FROM alpine:3.12

COPY --from=ubuntuBuilder /sourcepkg/* /sourcepkg/
COPY --from=debianBuilder /binaries/* /binaries/

# Hack: use volumes to "exfiltrate" the source files back to the host machine.
# This is just a marker directory to avoid mistakes when mounting volumes.
RUN mkdir -p /exfiltrate_to/empty

# Simple script to exfiltrate on run.
COPY docker/exfiltrate.sh /opt/exfiltrate.sh
CMD /opt/exfiltrate.sh
