name: Deploy
on:
  push:
    branches: [ 'adoptium' ] # Run on pushes to main adoptium only

jobs:
  build:
    runs-on: ubuntu-latest # github runners.
    steps:

      - name: Install dependencies
        run: |
          echo 'man-db man-db/auto-update boolean false' | sudo debconf-set-selections
          sudo apt-get -y install devscripts debhelper dput reprepro eatmydata
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Checkout this repo/branch
        uses: actions/checkout@v2
        with:
          path: src

      - name: Checkout GitHub pages repo
        uses: actions/checkout@v2 # https://github.com/actions/checkout#usage
        with:
          repository: rpardini/adoptium-deb-installer
          ref: "repo-adoptium" # branch
          path: src/repo

      - name: Configure git identity for apt repo repo
        working-directory: src/repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Set up Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@8c43807e82148a7bafc633cc9584d04bf54be8d0 # v4 # https://github.com/crazy-max/ghaction-import-gpg#usage
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Show GPG user IDs
        run: |
          echo "fingerprint: ${{ steps.import_gpg.outputs.fingerprint }}"
          echo "keyid:       ${{ steps.import_gpg.outputs.keyid }}"
          echo "name:        ${{ steps.import_gpg.outputs.name }}"
          echo "email:       ${{ steps.import_gpg.outputs.email }}"

      - name: Build and deploy
        working-directory: src
        run: ./publish.sh
        env:
          CLEAN_APT_REPO: 0 # 1 will remove all packages, and only re-add those newly built
          PUSH_APT_REPO: 1
          DPUT_LAUNCHPAD: 1
          PACKAGE_SIGNER_NAME: "${{ steps.import_gpg.outputs.name }} (Used for package signing)" # key comment, if any, seems required
          PACKAGE_SIGNER_EMAIL: ${{ steps.import_gpg.outputs.email }}
          PACKAGE_SIGNER_KEYID: ${{ steps.import_gpg.outputs.keyid }} # key reference, used by reprepro

