name: Deploy
on:
  push:
    branches: [ 'adoptium' ] # Run on pushes to main adoptium only

jobs:
  build:
    runs-on: ubuntu-latest # github runners.
    steps:

      - name: Checkout this repo/branch
        uses: actions/checkout@v2
        with:
          path: src

      - name: Checkout GitHub pages repo
        uses: actions/checkout@v2 # https://github.com/actions/checkout#usage
        with:
          repository: rpardini/adoptium-deb-installer
          ref: "repo-adoptium" # branch
          path: src/repo

      - name: Set up Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Show GPG user IDs
        run: |
          echo "fingerprint: ${{ steps.import_gpg.outputs.fingerprint }}"
          echo "keyid:       ${{ steps.import_gpg.outputs.keyid }}"
          echo "name:        ${{ steps.import_gpg.outputs.name }}"
          echo "email:       ${{ steps.import_gpg.outputs.email }}"

      - name: Build and deploy
        working-directory: src
        run: ./publish.sh
        env:
          CLEAN_APT_REPO: 1
          PUSH_APT_REPO: 1
          DPUT_LAUNCHPAD: 1
          PACKAGE_SIGNER_NAME: ${{ steps.import_gpg.outputs.name }}
          PACKAGE_SIGNER_EMAIL: ${{ steps.import_gpg.outputs.email }}

